services:
  react:
    image: node:23-alpine
    working_dir: /app
    volumes:
      - ./react-with-ts:/app
    ports:
      - "8080:8080"
    command: sh -c 'npm i && npm run dev'
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api
    networks:
      - app-network

  api:
    image: node:23-alpine
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    command: sh -c "npm i && npm run drizzle && npm run dev"
    environment:
      # DB_HOST: mysql_db
      # DB_USER: root
      # DB_PASSWORD: password
      # DB_NAME: users
      # DB_PORT: 3306
      DATABASE_URL: mysql://root:password@mysql_db:3306/reviews
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - mysql_db
    networks:
      - app-network

  mysql_db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: reviews
    volumes:
      # - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - bd_data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - react
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  bd_data:
